"""Cross-version fixture tests for OqHdf5Reader.

Parametrizes over every fixture directory under
``tests/fixtures/oq_cross_version/{classical,disaggregation}/oq_*/``
and drives the full extraction pipeline against each one.  The goal is to
verify that OqHdf5Reader handles every OQ HDF5 dialect correctly — not to
check OQ engine numerics (which legitimately differ across versions).

Fixtures are generated by ``scripts/regen_oq_fixtures.py``.  If the
directory is absent or empty, the parametrize list is [] and pytest reports
"no tests collected" rather than failing.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from toshi_hazard_store.model.constraints import ProbabilityEnum
from toshi_hazard_store.model.pyarrow.dataset_schema import (
    get_disagg_realisation_schema,
    get_hazard_realisation_schema,
)
from toshi_hazard_store.model.revision_4 import extract_classical_hdf5, extract_disagg_hdf5
from toshi_hazard_store.oq_import.h5py_reader import OqHdf5Reader

_FIXTURE_ROOT = Path(__file__).parent.parent / 'fixtures/oq_cross_version'

_HAZARD_MODEL_ID = 'TEST_MODEL_v0'
_TARGET_AGGR = 'mean'


def _discover_fixture_dirs(mode: str) -> list[Path]:
    root = _FIXTURE_ROOT / mode
    if not root.exists():
        return []
    return sorted(d for d in root.glob('oq_*') if (d / 'manifest.json').exists() and (d / 'calc.hdf5').exists())


# ── Classical ──────────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_extraction_cross_version(fixture_dir):
    """Schema, row count and curve values are sane across all OQ versions."""
    manifest = json.loads((fixture_dir / 'manifest.json').read_text())
    hdf5 = fixture_dir / 'calc.hdf5'
    oq_ver = manifest['oq_version']

    reader = extract_classical_hdf5.rlzs_to_record_batch_reader(
        str(hdf5),
        calculation_id='test-calc-id',
        compatible_calc_id='compat-0',
        producer_digest='sha256:' + 'a' * 64,
        config_digest='cfg-abc123',
    )

    assert reader.schema.equals(get_hazard_realisation_schema()), f'[OQ {oq_ver}] schema mismatch'

    batches = list(reader)
    assert len(batches) > 0, f'[OQ {oq_ver}] no batches yielded'
    total_rows = sum(b.num_rows for b in batches)
    assert total_rows > 0, f'[OQ {oq_ver}] zero rows'

    for batch in batches:
        for row_vals in batch.column('values').to_pylist():
            arr = np.asarray(row_vals, dtype=np.float64)
            assert np.all(np.isfinite(arr)), f'[OQ {oq_ver}] non-finite hazard values'
            assert np.all(arr >= 0), f'[OQ {oq_ver}] negative hazard values'


# ── Disaggregation ─────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_extraction_cross_version(fixture_dir):
    """Schema, row count and disagg values are sane across all OQ versions."""
    manifest = json.loads((fixture_dir / 'manifest.json').read_text())
    hdf5 = fixture_dir / 'calc.hdf5'
    oq_ver = manifest['oq_version']

    reader_h5 = OqHdf5Reader(str(hdf5))
    oqp = reader_h5.oqparam()
    kinds = oqp.get('disagg_outputs', [])
    kind = next((k for k in kinds if 'Mag' in k and 'Dist' in k), kinds[0])

    iml_disagg = oqp.get('iml_disagg', {})
    if len(iml_disagg) != 1:
        pytest.skip(
            f'[OQ {oq_ver}] fixture has {len(iml_disagg)} IMTs in iml_disagg '
            f'({list(iml_disagg)}); disaggs_to_record_batch_reader requires exactly 1. '
            f'Regenerate: uv run python scripts/regen_oq_fixtures.py '
            f'--version {oq_ver} --mode disaggregation --force'
        )

    reader = extract_disagg_hdf5.disaggs_to_record_batch_reader(
        hdf5_file=str(hdf5),
        calculation_id='test-calc-id',
        compatible_calc_id='compat-0',
        producer_digest='sha256:' + 'a' * 64,
        config_digest='cfg-abc123',
        probability=ProbabilityEnum._2_PCT_IN_50YRS,
        hazard_model_id=_HAZARD_MODEL_ID,
        target_aggr=_TARGET_AGGR,
        kind=kind,
    )

    assert reader.schema.equals(get_disagg_realisation_schema()), f'[OQ {oq_ver}] schema mismatch'

    probe = reader_h5.disagg_rlzs(kind)
    n_rlz = len(probe.extra)
    n_cells_per_rlz = probe.array.size // n_rlz

    batches = list(reader)
    total_rows = sum(b.num_rows for b in batches)
    assert total_rows == n_rlz, f'[OQ {oq_ver}] expected {n_rlz} rows, got {total_rows}'

    for batch in batches:
        values_col = batch.column('disagg_values')
        for i in range(batch.num_rows):
            arr = np.asarray(values_col[i].as_py(), dtype=np.float64)
            assert len(arr) == n_cells_per_rlz, f'[OQ {oq_ver}] disagg_values length {len(arr)} != {n_cells_per_rlz}'
            assert np.all(np.isfinite(arr)), f'[OQ {oq_ver}] non-finite disagg values'
            assert arr.sum() > 0, f'[OQ {oq_ver}] all-zero disagg row'
