"""Cross-version fixture tests for OqHdf5Reader.

Parametrizes over every fixture directory under
``tests/fixtures/oq_cross_version/{classical,disaggregation}/oq_*/``
and drives the full extraction pipeline against each one.  The goal is to
verify that OqHdf5Reader handles every OQ HDF5 dialect correctly — not to
check OQ engine numerics (which legitimately differ across versions).

Fixtures are generated by ``scripts/regen_oq_fixtures.py``.  If the
directory is absent or empty, the parametrize list is [] and pytest reports
"no tests collected" rather than failing.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from toshi_hazard_store.model.constraints import ProbabilityEnum
from toshi_hazard_store.model.pyarrow.dataset_schema import (
    get_disagg_realisation_schema,
    get_hazard_realisation_schema,
)
from toshi_hazard_store.model.revision_4 import extract_classical_hdf5, extract_disagg_hdf5
from toshi_hazard_store.oq_import.h5py_reader import OqHdf5Reader

_FIXTURE_ROOT = Path(__file__).parent.parent / 'fixtures/oq_cross_version'
_REF_CLASSICAL_HDF5 = _FIXTURE_ROOT / 'classical' / 'oq_3.25.1' / 'calc.hdf5'
_REF_DISAGG_HDF5 = _FIXTURE_ROOT / 'disaggregation' / 'oq_3.25.1' / 'calc.hdf5'

_HAZARD_MODEL_ID = 'TEST_MODEL_v0'
_TARGET_AGGR = 'mean'


def _discover_fixture_dirs(mode: str) -> list[Path]:
    root = _FIXTURE_ROOT / mode
    if not root.exists():
        return []
    return sorted(d for d in root.glob('oq_*') if (d / 'manifest.json').exists() and (d / 'calc.hdf5').exists())


# ── Classical ──────────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_extraction_cross_version(fixture_dir):
    """Schema, row count and curve values are sane across all OQ versions."""
    manifest = json.loads((fixture_dir / 'manifest.json').read_text())
    hdf5 = fixture_dir / 'calc.hdf5'
    oq_ver = manifest['oq_version']

    reader = extract_classical_hdf5.rlzs_to_record_batch_reader(
        str(hdf5),
        calculation_id='test-calc-id',
        compatible_calc_id='compat-0',
        producer_digest='sha256:' + 'a' * 64,
        config_digest='cfg-abc123',
    )

    assert reader.schema.equals(get_hazard_realisation_schema()), f'[OQ {oq_ver}] schema mismatch'

    batches = list(reader)
    assert len(batches) > 0, f'[OQ {oq_ver}] no batches yielded'
    total_rows = sum(b.num_rows for b in batches)
    assert total_rows > 0, f'[OQ {oq_ver}] zero rows'

    for batch in batches:
        for row_vals in batch.column('values').to_pylist():
            arr = np.asarray(row_vals, dtype=np.float64)
            assert np.all(np.isfinite(arr)), f'[OQ {oq_ver}] non-finite hazard values'
            assert np.all(arr >= 0), f'[OQ {oq_ver}] negative hazard values'


# ── Disaggregation ─────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_extraction_cross_version(fixture_dir):
    """Schema, row count and disagg values are sane across all OQ versions."""
    manifest = json.loads((fixture_dir / 'manifest.json').read_text())
    hdf5 = fixture_dir / 'calc.hdf5'
    oq_ver = manifest['oq_version']

    reader_h5 = OqHdf5Reader(str(hdf5))
    oqp = reader_h5.oqparam()
    kinds = oqp.get('disagg_outputs', [])
    kind = next((k for k in kinds if 'Mag' in k and 'Dist' in k), kinds[0])

    iml_disagg = oqp.get('iml_disagg', {})
    if len(iml_disagg) != 1:
        pytest.skip(
            f'[OQ {oq_ver}] fixture has {len(iml_disagg)} IMTs in iml_disagg '
            f'({list(iml_disagg)}); disaggs_to_record_batch_reader requires exactly 1. '
            f'Regenerate: uv run python scripts/regen_oq_fixtures.py '
            f'--version {oq_ver} --mode disaggregation --force'
        )

    reader = extract_disagg_hdf5.disaggs_to_record_batch_reader(
        hdf5_file=str(hdf5),
        calculation_id='test-calc-id',
        compatible_calc_id='compat-0',
        producer_digest='sha256:' + 'a' * 64,
        config_digest='cfg-abc123',
        probability=ProbabilityEnum._2_PCT_IN_50YRS,
        hazard_model_id=_HAZARD_MODEL_ID,
        target_aggr=_TARGET_AGGR,
        kind=kind,
    )

    assert reader.schema.equals(get_disagg_realisation_schema()), f'[OQ {oq_ver}] schema mismatch'

    probe = reader_h5.disagg_rlzs(kind)
    n_rlz = len(probe.extra)
    n_cells_per_rlz = probe.array.size // n_rlz

    batches = list(reader)
    total_rows = sum(b.num_rows for b in batches)
    assert total_rows == n_rlz, f'[OQ {oq_ver}] expected {n_rlz} rows, got {total_rows}'

    for batch in batches:
        values_col = batch.column('disagg_values')
        for i in range(batch.num_rows):
            arr = np.asarray(values_col[i].as_py(), dtype=np.float64)
            assert len(arr) == n_cells_per_rlz, f'[OQ {oq_ver}] disagg_values length {len(arr)} != {n_cells_per_rlz}'
            assert np.all(np.isfinite(arr)), f'[OQ {oq_ver}] non-finite disagg values'
            assert arr.sum() > 0, f'[OQ {oq_ver}] all-zero disagg row'


# ── Reader-correctness invariant tests (classical) ─────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_imt_axis_matches_stored_attrs(fixture_dir):
    """IMTs returned by the reader pipeline match the axis labels stored in hcurves-rlzs attrs.

    Catches the case where OQ changes the IMT storage order while the reader
    still applies sorted(hazard_imtls.keys()), silently permuting the imt axis.
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'

    reader = OqHdf5Reader(str(hdf5))
    oqparam = reader.oqparam()
    hazard_imtls = oqparam.get('hazard_imtls') or oqparam.get('intensity_measure_types_and_levels', {})
    reader_imts = sorted(list(hazard_imtls.keys()))  # mirrors extract_classical_hdf5.py

    with h5py.File(hdf5, 'r') as f:
        stored_imts = json.loads(f['hcurves-rlzs'].attrs['json'])['imt']

    assert reader_imts == stored_imts, f'[OQ {oq_ver}] IMT axis mismatch: reader {reader_imts} != stored {stored_imts}'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_rlz_curves_match_raw_hdf5(fixture_dir):
    """Per-rlz curves from OqHdf5Reader are bitwise-equal to raw HDF5 slices for a sample of rlzs.

    Picks a few rlzs with non-zero curves (all-zero rlzs are not diagnostic).
    Catches rlz key → axis-index mapping errors and axis transpositions in
    hcurves-rlzs without any floating-point tolerance.
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'

    reader = OqHdf5Reader(str(hdf5))
    rlzs_dict = reader.hcurves_rlzs()  # {rlz-NNN: (n_sites, n_imts, n_levels)}
    n_rlz = len(rlzs_dict)
    n_digits = max(3, len(str(n_rlz - 1)))

    with h5py.File(hdf5, 'r') as f:
        raw_cube = f['hcurves-rlzs'][()]  # (n_sites, n_rlz, n_imts, n_levels)

    # Sample first, middle and last of non-zero rlzs — all-zero rlzs are not diagnostic.
    non_zero = [i for i in range(n_rlz) if raw_cube[:, i, :, :].sum() > 0]
    assert non_zero, f'[OQ {oq_ver}] all rlzs have zero hazard curves — fixture is degenerate'
    n_sample = min(3, len(non_zero))
    step = max(1, len(non_zero) // n_sample)
    sample_ordinals = non_zero[::step][:n_sample]

    for i in sample_ordinals:
        key = f'rlz-{i:0{n_digits}d}'
        expected = raw_cube[:, i, :, :]  # (n_sites, n_imts, n_levels)
        actual = rlzs_dict[key]
        assert np.array_equal(actual, expected), (
            f'[OQ {oq_ver}] rlz ordinal {i} ({key}) does not match raw HDF5 slice — '
            f'rlz key/index mapping or axis order is wrong. '
            f'max diff: {np.abs(actual - expected).max():.3e}'
        )


# ── Reader-correctness invariant tests (disaggregation) ───────────────────────


def _disagg_kind(fixture_dir: Path) -> str:
    """Return the first Mag+Dist disagg kind available in this fixture."""
    reader = OqHdf5Reader(str(fixture_dir / 'calc.hdf5'))
    kinds = reader.oqparam().get('disagg_outputs', [])
    return next((k for k in kinds if 'Mag' in k and 'Dist' in k), kinds[0])


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_shape_descr_matches_stored_attrs(fixture_dir):
    """Reader's shape_descr for disagg matches the axis names stored in the dataset attrs.

    Catches re-ordering of axes inside disagg-rlzs/<kind> and wrong axis parsing
    from the kind string.
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'
    kind = _disagg_kind(fixture_dir)

    with h5py.File(hdf5, 'r') as f:
        ds_attrs = f[f'disagg-rlzs/{kind}'].attrs
        if 'shape_descr' not in ds_attrs:
            pytest.skip(f'[OQ {oq_ver}] disagg-rlzs has no shape_descr attr — OQ < 3.24')
        raw = ds_attrs['shape_descr']
        stored_axes = [v.decode() if isinstance(v, bytes) else str(v) for v in raw]

    probe = OqHdf5Reader(str(hdf5)).disagg_rlzs(kind)
    reader_shape_descr = probe.shape_descr  # e.g. ['trt', 'mag', 'dist', 'eps', 'imt', 'poe']

    # Drop 'site_id' (sliced out by the reader) and 'Z' (rlz axis, surfaced via .extra).
    expected = [a.lower() for a in stored_axes if a not in ('site_id', 'Z')]

    assert reader_shape_descr == expected, (
        f'[OQ {oq_ver}] disagg shape_descr mismatch: reader {reader_shape_descr} != stored {expected}'
    )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_bin_edge_count_matches_axis_sizes(fixture_dir):
    """For each numeric kind-axis: n_bin_edges == axis_size + 1.

    Catches the case where OQ starts storing bin centres instead of edges (or
    vice versa), which would make our midpoint calculation wrong and produce
    bin labels shifted by half a bin width.
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'
    kind = _disagg_kind(fixture_dir)

    # Axes are encoded in the kind string — no need for shape_descr attr.
    kind_axes = kind.split('_')  # e.g. ['TRT', 'Mag', 'Dist', 'Eps']
    with h5py.File(hdf5, 'r') as f:
        ds = f[f'disagg-rlzs/{kind}']
        for pos, ax_name in enumerate(kind_axes, start=1):
            axis_size = ds.shape[pos]
            if ax_name in f['disagg-bins']:
                edges = f[f'disagg-bins/{ax_name}'][()]
                # Only numeric axes use the edges→midpoints convention;
                # string/categorical axes (e.g. TRT) store labels directly.
                if edges.ndim == 1 and edges.dtype.kind in ('f', 'u', 'i'):
                    n_midpoints = len(edges) - 1
                    assert n_midpoints == axis_size, (
                        f'[OQ {oq_ver}] disagg-bins/{ax_name}: '
                        f'n_edges={len(edges)} → n_midpoints={n_midpoints} != axis_size={axis_size}. '
                        f'OQ may have switched from edges to centres.'
                    )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_rlz_slices_match_raw_hdf5(fixture_dir):
    """Per-rlz disagg slices match raw HDF5, and .extra labels match best_rlzs ordinals.

    The Z axis in disagg-rlzs is indexed by best_rlzs[site_idx] ordering, not by
    rlz ordinal. Verifies:
    1. probe.array column j is bitwise-equal to raw_cube[..., j] for a sample of
       non-zero rlz positions.
    2. probe.extra[j] correctly translates position j to ordinal via best_rlzs.

    Catches Z-axis position mis-mapping and best_rlzs → label translation errors.
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'
    kind = _disagg_kind(fixture_dir)

    probe = OqHdf5Reader(str(hdf5)).disagg_rlzs(kind)  # default site_idx=0, imt_idx=0, poe_idx=0

    with h5py.File(hdf5, 'r') as f:
        raw = f[f'disagg-rlzs/{kind}'][()]  # (n_sites, *kind_axes, n_imt, n_poe, n_rlz)
        best_rlzs = f['best_rlzs'][()]  # (n_sites, n_rlz)

    expected_full = raw[0, ..., 0:1, 0:1, :]  # site=0, imt=0:1, poe=0:1 → (*kind_axes, 1, 1, n_rlz)
    assert probe.array.shape == expected_full.shape, (
        f'[OQ {oq_ver}] disagg probe shape {probe.array.shape} != expected {expected_full.shape}'
    )

    # Sample non-zero rlz positions along the Z axis (last).
    rlz_sums = expected_full.reshape(-1, expected_full.shape[-1]).sum(axis=0)
    non_zero = [j for j in range(rlz_sums.shape[0]) if rlz_sums[j] > 0]
    assert non_zero, f'[OQ {oq_ver}] all disagg rlz columns are zero — fixture is degenerate'
    n_sample = min(3, len(non_zero))
    step = max(1, len(non_zero) // n_sample)
    sample_positions = non_zero[::step][:n_sample]

    for j in sample_positions:
        expected_slice = expected_full[..., j]
        actual_slice = probe.array[..., j]
        assert np.array_equal(actual_slice, expected_slice), (
            f'[OQ {oq_ver}] disagg Z position {j} does not match raw slice — '
            f'Z-axis mapping or array layout is wrong. '
            f'max diff: {np.abs(actual_slice - expected_slice).max():.3e}'
        )
        expected_label = f'rlz{int(best_rlzs[0, j])}'
        assert probe.extra[j] == expected_label, (
            f'[OQ {oq_ver}] disagg .extra[{j}]={probe.extra[j]!r} != {expected_label!r} '
            f'from best_rlzs — label translation is wrong.'
        )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_best_rlzs_valid_ordinals(fixture_dir):
    """best_rlzs entries are valid rlz ordinals in [0, n_rlz) with no duplicates per site.

    Catches the case where OQ changes the semantics of best_rlzs (e.g., storing
    weights instead of ordinals, or 1-based indexing).
    """
    import h5py

    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    hdf5 = fixture_dir / 'calc.hdf5'

    with h5py.File(hdf5, 'r') as f:
        n_rlz = f['weights'].shape[0]
        best = f['best_rlzs'][()]  # (n_sites, n_rlz)

    assert best.min() >= 0, f'[OQ {oq_ver}] best_rlzs has negative ordinals'
    assert best.max() < n_rlz, f'[OQ {oq_ver}] best_rlzs max={best.max()} >= n_rlz={n_rlz}'
    for site_idx in range(best.shape[0]):
        assert len(set(best[site_idx])) == n_rlz, (
            f'[OQ {oq_ver}] best_rlzs[{site_idx}] has duplicate ordinals — expected a permutation of 0..{n_rlz - 1}'
        )


# ── OqHdf5Reader method tests — cross-version vs 3.25.1 reference ─────────────
#
# These tests exercise every public method of OqHdf5Reader against all 7 OQ
# version fixtures, using oq_3.25.1 as the reference.  3.25.1 compares against
# itself (trivial self-check).  Where values drift legitimately across engine
# versions (hcurves, disagg arrays), structure is checked instead; numerical
# accuracy vs a version's own HDF5 is covered by the reader-correctness tests
# above. Structural checks + existing per-version slice tests together provide
# complete coverage.


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_oqparam_classical(fixture_dir):
    """oqparam keys consumed by extract_classical_hdf5 are present and consistent across OQ versions."""
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    reader = OqHdf5Reader(str(fixture_dir / 'calc.hdf5'))
    oqparam = reader.oqparam()

    assert oqparam.get('calculation_mode') == 'classical', f'[OQ {oq_ver}] calculation_mode'

    hazard_imtls = oqparam.get('hazard_imtls') or oqparam.get('intensity_measure_types_and_levels')
    assert hazard_imtls, f'[OQ {oq_ver}] neither hazard_imtls nor intensity_measure_types_and_levels present'
    assert len(hazard_imtls) > 0, f'[OQ {oq_ver}] hazard_imtls is empty'

    ref_oqparam = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).oqparam()
    ref_imtls = ref_oqparam.get('hazard_imtls') or ref_oqparam.get('intensity_measure_types_and_levels')
    assert sorted(hazard_imtls.keys()) == sorted(ref_imtls.keys()), (
        f'[OQ {oq_ver}] IMT keys differ from reference: {sorted(hazard_imtls.keys())} != {sorted(ref_imtls.keys())}'
    )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_oqhdf5reader_oqparam_disagg(fixture_dir):
    """oqparam keys consumed by extract_disagg_hdf5 are present and consistent across OQ versions."""
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    reader = OqHdf5Reader(str(fixture_dir / 'calc.hdf5'))
    oqparam = reader.oqparam()

    assert oqparam.get('calculation_mode') == 'disaggregation', f'[OQ {oq_ver}] calculation_mode'

    ref_oqparam = OqHdf5Reader(str(_REF_DISAGG_HDF5)).oqparam()

    disagg_outputs = oqparam.get('disagg_outputs', [])
    assert disagg_outputs == ref_oqparam.get('disagg_outputs', []), (
        f'[OQ {oq_ver}] disagg_outputs mismatch: {disagg_outputs}'
    )

    iml_disagg = oqparam.get('iml_disagg', {})
    assert sorted(iml_disagg.keys()) == sorted(ref_oqparam.get('iml_disagg', {}).keys()), (
        f'[OQ {oq_ver}] iml_disagg IMT keys differ from reference'
    )
    assert len(next(iter(iml_disagg.values()))) == 1, (
        f'[OQ {oq_ver}] iml_disagg must have exactly one IML per IMT'
    )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_sitecol(fixture_dir):
    """sitecol() returns the same lat/lon/vs30 as the reference — same sites.csv across all OQ versions."""
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    df = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).sitecol()
    ref_df = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).sitecol()

    assert df.shape == ref_df.shape, f'[OQ {oq_ver}] sitecol shape {df.shape} != ref {ref_df.shape}'
    assert list(df['lat']) == list(ref_df['lat']), f'[OQ {oq_ver}] sitecol lat mismatch'
    assert list(df['lon']) == list(ref_df['lon']), f'[OQ {oq_ver}] sitecol lon mismatch'
    assert list(df['vs30']) == list(ref_df['vs30']), f'[OQ {oq_ver}] sitecol vs30 mismatch'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_hcurves_rlzs_structure(fixture_dir):
    """hcurves_rlzs() returns the same key set and per-key shapes as the reference.

    Values drift is too large relative on meaningful PoEs across OQ engine versions —
    Numerical accuracy is verified per-version by test_classical_rlz_curves_match_raw_hdf5.
    """
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    rlzs = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).hcurves_rlzs()
    ref_rlzs = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).hcurves_rlzs()

    assert set(rlzs.keys()) == set(ref_rlzs.keys()), (
        f'[OQ {oq_ver}] hcurves_rlzs key set differs from reference'
    )
    for key in ref_rlzs:
        assert rlzs[key].shape == ref_rlzs[key].shape, (
            f'[OQ {oq_ver}] hcurves_rlzs[{key}] shape {rlzs[key].shape} != ref {ref_rlzs[key].shape}'
        )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_gsim_branches(fixture_dir):
    """gsim_branches() returns the same branch IDs and equivalent uncertainty strings.

    Branch IDs are identical across all OQ versions.  Uncertainty string values
    differ only in whitespace (OQ 3.25 added spaces around = in GSIM params);
    comparison is done after stripping all whitespace.
    """
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    branches = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).gsim_branches()
    ref_branches = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).gsim_branches()

    assert set(branches.keys()) == set(ref_branches.keys()), (
        f'[OQ {oq_ver}] gsim_branches key set differs from reference'
    )
    for key in ref_branches:
        assert branches[key].replace(' ', '') == ref_branches[key].replace(' ', ''), (
            f'[OQ {oq_ver}] gsim_branches[{key!r}] content mismatch after whitespace normalisation'
        )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_source_branches(fixture_dir):
    """source_branches() returns an identical dict across all OQ versions."""
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    branches = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).source_branches()
    ref_branches = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).source_branches()

    assert branches == ref_branches, (
        f'[OQ {oq_ver}] source_branches differs from reference'
    )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_oqhdf5reader_realizations(fixture_dir):
    """realizations() returns the same ordinals, source paths and gsim paths across all OQ versions."""
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    rlzs = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).realizations()
    ref_rlzs = OqHdf5Reader(str(_REF_CLASSICAL_HDF5)).realizations()

    assert len(rlzs) == len(ref_rlzs), (
        f'[OQ {oq_ver}] realizations count {len(rlzs)} != ref {len(ref_rlzs)}'
    )
    for r, ref_r in zip(rlzs, ref_rlzs):
        assert r.ordinal == ref_r.ordinal, f'[OQ {oq_ver}] ordinal mismatch at position {r.ordinal}'
        assert r.source_path == ref_r.source_path, (
            f'[OQ {oq_ver}] source_path mismatch at ordinal {r.ordinal}'
        )
        assert r.gsim_path == ref_r.gsim_path, (
            f'[OQ {oq_ver}] gsim_path mismatch at ordinal {r.ordinal}'
        )


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_oqhdf5reader_disagg_rlzs_structure(fixture_dir):
    """disagg_rlzs() returns a DisaggExtract with the same structure as the reference.

    Values drift 22-382× relative across OQ engine versions — too large for
    cross-version numerical comparison.  Numerical accuracy is verified
    per-version by test_disagg_rlz_slices_match_raw_hdf5.
    """
    oq_ver = json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']
    reader = OqHdf5Reader(str(fixture_dir / 'calc.hdf5'))
    kinds = reader.oqparam().get('disagg_outputs', [])
    kind = next((k for k in kinds if 'Mag' in k and 'Dist' in k), kinds[0])

    probe = reader.disagg_rlzs(kind)
    ref_probe = OqHdf5Reader(str(_REF_DISAGG_HDF5)).disagg_rlzs(kind)

    assert probe.array.shape == ref_probe.array.shape, (
        f'[OQ {oq_ver}] DisaggExtract.array.shape {probe.array.shape} != ref {ref_probe.array.shape}'
    )
    assert probe.shape_descr == ref_probe.shape_descr, (
        f'[OQ {oq_ver}] DisaggExtract.shape_descr {probe.shape_descr} != ref {ref_probe.shape_descr}'
    )
    assert len(probe.extra) == len(ref_probe.extra), (
        f'[OQ {oq_ver}] DisaggExtract.extra length {len(probe.extra)} != ref {len(ref_probe.extra)}'
    )
    for label in probe.extra:
        assert label.startswith('rlz'), f'[OQ {oq_ver}] extra label {label!r} not in rlzN format'
    kind_axes = [ax.lower() for ax in kind.split('_')]
    for ax in kind_axes:
        test_bins = getattr(probe, ax)
        ref_bins = getattr(ref_probe, ax)
        assert len(test_bins) == len(ref_bins), (
            f'[OQ {oq_ver}] DisaggExtract.{ax} bin count {len(test_bins)} != ref {len(ref_bins)}'
        )
