"""Cross-version snapshot tests: OqHdf5Reader vs OQ Extractor output.

For each fixture under tests/fixtures/oq_cross_version/{classical,disaggregation}/oq_*/
that has a pre-baked extractor_snapshot.npz + extractor_snapshot.json (generated by
scripts/regen_oq_fixtures.py → scripts/extract_snapshot.py inside the same OQ engine
Docker container that produced calc.hdf5), asserts that OqHdf5Reader produces
numerically identical output.

No engine-drift problem: the snapshot was captured from the same version of OQ that
wrote calc.hdf5 so both sides of the comparison reflect the same engine semantics.
No host-side OQ install needed: the snapshot is pre-baked and committed alongside
the HDF5.

If a snapshot is missing for a fixture (e.g. the fixture was created before snapshot
support was added), that case is skipped with an actionable message.  To populate
all snapshots:

    uv run python scripts/regen_oq_fixtures.py --mode both --force
"""

import json
from pathlib import Path

import numpy as np
import pytest

from toshi_hazard_store.oq_import.h5py_reader import OqHdf5Reader

_FIXTURE_ROOT = Path(__file__).parent.parent / 'fixtures/oq_cross_version'


def _discover_fixture_dirs(mode: str) -> list[Path]:
    root = _FIXTURE_ROOT / mode
    if not root.exists():
        return []
    return sorted(d for d in root.glob('oq_*') if (d / 'manifest.json').exists() and (d / 'calc.hdf5').exists())


def _oq_ver(fixture_dir: Path) -> str:
    return json.loads((fixture_dir / 'manifest.json').read_text())['oq_version']


def _require_snapshot(fixture_dir: Path, oq_ver: str) -> None:
    npz = fixture_dir / 'extractor_snapshot.npz'
    jsn = fixture_dir / 'extractor_snapshot.json'
    if not npz.exists() or not jsn.exists():
        pytest.skip(
            f'[OQ {oq_ver}] Extractor snapshot not present — regenerate: '
            f'uv run python scripts/regen_oq_fixtures.py --version {oq_ver} --mode ... --force'
        )


def _load_snapshot(fixture_dir: Path):
    """Return (npz_file, sidecar_dict)."""
    npz = np.load(str(fixture_dir / 'extractor_snapshot.npz'), allow_pickle=False)
    sidecar = json.loads((fixture_dir / 'extractor_snapshot.json').read_text())
    return npz, sidecar


# ── Classical ──────────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_snapshot_oqparam(fixture_dir):
    """oqparam dict from OqHdf5Reader is identical to the Extractor's output."""
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    _, sidecar = _load_snapshot(fixture_dir)

    reader_oqp = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).oqparam()
    snap_oqp = json.loads(sidecar['oqparam_json'])
    assert reader_oqp == snap_oqp, f'[OQ {oq_ver}] oqparam mismatch'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_snapshot_sitecol(fixture_dir):
    """sitecol lat/lon/vs30 from OqHdf5Reader match the Extractor snapshot."""
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    npz, _ = _load_snapshot(fixture_dir)

    df = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).sitecol()
    assert np.allclose(df['lat'].values, npz['sitecol__lat'], rtol=1e-5), f'[OQ {oq_ver}] sitecol lat'
    assert np.allclose(df['lon'].values, npz['sitecol__lon'], rtol=1e-5), f'[OQ {oq_ver}] sitecol lon'
    assert np.allclose(df['vs30'].values, npz['sitecol__vs30'], rtol=1e-5), f'[OQ {oq_ver}] sitecol vs30'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_snapshot_realizations(fixture_dir):
    """realizations() ordinals and paths match the Extractor snapshot.

    A permutation in a future OQ version that reorders rlzs in sm_data / gsim_lt
    will cause this test to fail.
    """
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    _, sidecar = _load_snapshot(fixture_dir)

    rlzs = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).realizations()
    snap_rlzs = sidecar['realizations']
    assert len(rlzs) == len(snap_rlzs), f'[OQ {oq_ver}] realization count {len(rlzs)} != {len(snap_rlzs)}'
    for i, (r, s) in enumerate(zip(rlzs, snap_rlzs)):
        assert r.ordinal == s['ordinal'], f'[OQ {oq_ver}] rlz[{i}] ordinal mismatch'
        assert r.source_path == tuple(s['sm_lt_path']), f'[OQ {oq_ver}] rlz[{i}] source_path mismatch'
        assert r.gsim_path == tuple(s['gsim_lt_path']), f'[OQ {oq_ver}] rlz[{i}] gsim_path mismatch'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('classical'), ids=lambda d: d.name)
def test_classical_snapshot_hcurves_rlzs(fixture_dir):
    """Per-rlz hazard curves from OqHdf5Reader match the Extractor snapshot numerically.

    A reordering of rlzs in hcurves-rlzs, an IMT-axis transposition, or a reader
    key/index mapping error will produce a mismatch here.
    """
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    npz, sidecar = _load_snapshot(fixture_dir)

    rlzs = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).hcurves_rlzs()
    snap_keys = sidecar['hcurves_rlzs_keys']
    assert set(rlzs.keys()) == set(snap_keys), f'[OQ {oq_ver}] hcurves_rlzs key set differs from snapshot'
    for key in snap_keys:
        npz_key = 'hcurves_rlzs__' + key.replace('-', '_')
        assert np.allclose(rlzs[key], npz[npz_key], rtol=1e-5), (
            f'[OQ {oq_ver}] hcurves_rlzs[{key!r}] mismatch — max abs diff: {np.abs(rlzs[key] - npz[npz_key]).max():.3e}'
        )


# ── Disaggregation ─────────────────────────────────────────────────────────────


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_snapshot_oqparam(fixture_dir):
    """oqparam dict from OqHdf5Reader is identical to the Extractor's output."""
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    _, sidecar = _load_snapshot(fixture_dir)

    reader_oqp = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).oqparam()
    snap_oqp = json.loads(sidecar['oqparam_json'])
    assert reader_oqp == snap_oqp, f'[OQ {oq_ver}] oqparam mismatch'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_snapshot_sitecol(fixture_dir):
    """sitecol lat/lon/vs30 from OqHdf5Reader match the Extractor snapshot."""
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    npz, _ = _load_snapshot(fixture_dir)

    df = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).sitecol()
    assert np.allclose(df['lat'].values, npz['sitecol__lat'], rtol=1e-5), f'[OQ {oq_ver}] sitecol lat'
    assert np.allclose(df['lon'].values, npz['sitecol__lon'], rtol=1e-5), f'[OQ {oq_ver}] sitecol lon'
    assert np.allclose(df['vs30'].values, npz['sitecol__vs30'], rtol=1e-5), f'[OQ {oq_ver}] sitecol vs30'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_snapshot_realizations(fixture_dir):
    """realizations() ordinals and paths match the Extractor snapshot.

    A permutation in a future OQ version that reorders rlzs will fail here.
    """
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    _, sidecar = _load_snapshot(fixture_dir)

    rlzs = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).realizations()
    snap_rlzs = sidecar['realizations']
    assert len(rlzs) == len(snap_rlzs), f'[OQ {oq_ver}] realization count {len(rlzs)} != {len(snap_rlzs)}'
    for i, (r, s) in enumerate(zip(rlzs, snap_rlzs)):
        assert r.ordinal == s['ordinal'], f'[OQ {oq_ver}] rlz[{i}] ordinal mismatch'
        assert r.source_path == tuple(s['sm_lt_path']), f'[OQ {oq_ver}] rlz[{i}] source_path mismatch'
        assert r.gsim_path == tuple(s['gsim_lt_path']), f'[OQ {oq_ver}] rlz[{i}] gsim_path mismatch'


@pytest.mark.parametrize('fixture_dir', _discover_fixture_dirs('disaggregation'), ids=lambda d: d.name)
def test_disagg_snapshot_disagg_rlzs(fixture_dir):
    """disagg_rlzs() array, rlz_labels and bin centres match the Extractor snapshot.

    Catches Z-axis reordering (rlz_labels mismatch), array layout changes, and
    bin-centre drift (which would shift computed disagg midpoints).

    shape_descr is not compared: OQ ≤3.23 collapses the singleton poe dim so
    the Extractor's shape_descr may have one fewer entry than the reader's
    canonical 7D form.  The array comparison uses np.squeeze() on both sides for
    the same reason, while still catching non-singleton shape bugs.
    """
    oq_ver = _oq_ver(fixture_dir)
    _require_snapshot(fixture_dir, oq_ver)
    npz, sidecar = _load_snapshot(fixture_dir)

    kind = sidecar['kind']
    probe_dict = OqHdf5Reader(str(fixture_dir / 'calc.hdf5')).disagg_rlzs(kind)

    # Reconstruct (*kind_bins, n_rlz) by squeezing imt/poe from each per-rlz entry then stacking.
    reader_arr = np.stack([e.array.squeeze() for e in probe_dict.values()], axis=-1)
    snap_arr = npz['disagg__array'].squeeze()
    assert reader_arr.shape == snap_arr.shape, (
        f'[OQ {oq_ver}] disagg array shape mismatch after squeeze: '
        f'reader {reader_arr.shape} != snapshot {snap_arr.shape}'
    )
    assert np.allclose(reader_arr, snap_arr, rtol=1e-5), (
        f'[OQ {oq_ver}] disagg array mismatch — max abs diff: {np.abs(reader_arr - snap_arr).max():.3e}'
    )
    # Snapshot stores OQ-format labels ('rlzN'); normalise to our 'rlz-NNN' format for comparison.
    n_rlz = len(probe_dict)
    n_digits = max(3, len(str(n_rlz - 1)))
    expected_keys = [f'rlz-{int(lbl[3:]):0{n_digits}d}' for lbl in sidecar['rlz_labels']]
    assert list(probe_dict.keys()) == expected_keys, f'[OQ {oq_ver}] rlz key mismatch'

    probe = next(iter(probe_dict.values()))
    snap_bins = sidecar['disagg_bins']
    for ax in kind.split('_'):
        ax_lo = ax.lower()
        h5_vals = [v.decode() if isinstance(v, bytes) else v for v in getattr(probe, ax_lo)]
        snap_vals = snap_bins[ax_lo]
        if snap_vals and isinstance(snap_vals[0], str):
            assert h5_vals == snap_vals, f'[OQ {oq_ver}] disagg_bins[{ax_lo}] string mismatch'
        else:
            assert np.allclose(h5_vals, snap_vals, rtol=1e-5), f'[OQ {oq_ver}] disagg_bins[{ax_lo}] numeric mismatch'
