name: dev workflow

# Controls when the action will run.
on:
  push:
    branches: [ main, pre-release* ]
  pull_request:
    branches: [ main, pre-release* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      operating-systems: "['ubuntu-latest', 'macos-latest']"
      python-versions: "['3.10', '3.11']"
      poetry-version: 1.8.4
    secrets: inherit
